[options]
girs_dir = "gir-files"
library = "GdkX11"
version = "3.0"
min_cfg_version = "3.14"
target_path = "."
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
  "GdkX11.X11AppLaunchContext",
  "GdkX11.X11Cursor",
  "GdkX11.X11DeviceCore",
  "GdkX11.X11DeviceManagerCore",
  "GdkX11.X11Display",
  "GdkX11.X11DisplayManager",
  "GdkX11.X11DragContext",
  "GdkX11.X11Keymap",
  "GdkX11.X11Screen",
  "GdkX11.X11Visual",
  "GdkX11.X11Window"
]

ignore = [
]

manual = [
  "Gdk.AppLaunchContext",
  "Gdk.Atom",
  "Gdk.Cursor",
  "Gdk.Device",
  "Gdk.DeviceManager",
  "Gdk.Display",
  "Gdk.DisplayManager",
  "Gdk.DragContext",
  "Gdk.GLContext",
  "Gdk.Keymap",
  "Gdk.Monitor",
  "Gdk.Screen",
  "Gdk.Visual",
  "Gdk.Window",
  "Gio.AppLaunchContext",
  "xlib.Atom",
  "xlib.Cursor",
  "xlib.Display",
  "xlib.Screen",
  "xlib.Visual",
  "xlib.VisualID",
  "xlib.Window",
  "xlib.XID",
]

[[object]]
name = "GdkX11.*"
status = "generate"

[[object]]
name = "GdkX11.X11DeviceXI2"
status = "generate"
generate_builder = true

[[object]]
name = "GdkX11.X11DeviceManagerXI2"
status = "generate"
generate_builder = true

[[object]]
name = "GdkX11.X11GLContext"
status = "generate"
version = "3.16"

[[object]]
name = "GdkX11.X11Monitor"
status = "generate"
version = "3.22"
